package com.cvbuilder.dto;

import lombok.*;
import java.util.List;

@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class UserProfileRequest {

    // Kişisel bilgiler
    private String fullName;
    private String phone;
    private String location;
    private String linkedinUrl;
    private String githubUrl;
    private String websiteUrl;

    // Özet / Başlık
    private String title;
    private Integer totalExperienceYear;
    private String summary;

    // Eğitim bilgileri
    private String educationSchool;
    //private String educationDegree;
   // private String educationDepartment;
    private String educationStartYear;
    private String educationEndYear;

    // Listeler
    private List<UserSkillDTO> skills;
    private List<UserExperienceDTO> experiences;
    
    

    // --- Yeni eklenenler ---
    private List<UserLanguageDTO> languages;
    private List<UserCertificateDTO> certificates;
    private List<UserProjectDTO> projects;
 // YENİ: Description seviyesi tercihi
    private String preferredDescriptionLevel; // "BEGINNER", "INTERMEDIATE", "EXPERT"
    private Boolean autoGenerateDescriptions; // Otomatik açıklama üretilsin mi?
}
